### PR TITLE
Tutorial updates 2019.4

### PR DESCRIPTION
**Pull request by justinshaffer**
Updates to the Qiita Tutorial, to mirror updates to QIIME2 2019.4

### CODE REVIEW

**Review by antgonza — APPROVED** [review]
Looks great, thanks!

**Comment by antgonza** [comment]
@justinshaffer, Just noticed that the zip file has conflicts, any idea?

**Comment by justinshaffer** [comment]
This is probably from the updated prep_info file with the added column
needed for deblur (platform == 'Illumina').

Does that sound right?

Justin

**Comment by antgonza** [comment]
Hi @justinshaffer,

Sorry for late reply. 

This is the first time that I see merge conflicts in binary files but it sounds like it's pretty common:
https://codeyarns.com/2016/04/11/how-to-resolve-git-conflict-with-binary-files/
https://lostechies.com/joshuaflanagan/2010/01/29/how-to-resolve-a-binary-file-conflict-with-git/

Anyway, after reading those links, I think you should run these commands in your local branch:
```
git pull upstream master
git checkout --ours -- docs/example_data/qiita-tutorial-16S-processing-dataset.zip
git add docs/example_data/qiita-tutorial-16S-processing-dataset.zip
git commit –m "adding zip file"
git push origin tutorial_updates_2019.4
```
Thanks.

**Comment by justinshaffer** [comment]
That first line of code seemed to generate an error. Here is what printed
to screen after running 'git show' and then 'git pull upstream master':

Justin-07:28:33-bash-3.2|cmi-workshops|$ git show
commit 916fefbf1d305eb725ab47fe5bdeacdc287c05b8 (HEAD ->
tutorial_updates_2019.4, origin/tutorial_updates_2019.4)
Author: Justin Shaffer <justinparkshaffer@gmail.com>
Date:   Sat May 11 12:16:06 2019 -0700

    Updated 16S processing prep into file

diff --git a/docs/example_data/qiita-tutorial-16S-processing-dataset.zip
b/docs/example_data/qiita-tutorial-16S-processing-dataset.zip
index 59abc22..56bbd31 100644
Binary files a/docs/example_data/qiita-tutorial-16S-processing-dataset.zip
and b/docs/example_data/qiita-tutorial-16S-processing-dataset.zip differ
Justin-07:29:22-bash-3.2|cmi-workshops|$ git pull upstream master
fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Pull request closed without merging**
